steps:
  # Deploy `upload-item` function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - upload-item
      - --runtime=python312
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=upload_item
      - --region=asia-east1
      - --source=./backend

  # Deploy `get-items` function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - get-items
      - --runtime=python312
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=get_items
      - --region=asia-east1
      - --source=./backend

timeout: 1200s  # 20 minutes timeout
